CakesByRAndRCore/Models/ManageUserRolesViewModel.cs
namespace CakesByRAndRCore.Models
{
    public class ManageUserRolesViewModel
    {

        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Selected { get; set; }

    }
}

CakesByRAndRCore/Controllers/AdminAndSetupController.cs
using CakesByRAndRCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Runtime.ConstrainedExecution;
using System.Xml.Linq;
using static CakesByRAndRCore.Models.StudentModel;
using Newtonsoft.Json.Serialization;
using CakesByRAndRCore.Repositories;
using System;
using Microsoft.EntityFrameworkCore;

namespace CakesByRAndRCore.Controllers
{

    [Authorize]
    public class AdminAndSetupController : Controller
    {

        //UnitOfWork unitOfWork = new UnitOfWork();

        private UserManager<AppUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

       // private readonly SignInManager<AppUser> signInManager;
        //private IPasswordHasher<AppUser> passwordHasher;


        public AdminAndSetupController(UserManager<AppUser> usrMgr, RoleManager<IdentityRole> roleMgr, IPasswordHasher<AppUser> passwordHash)
        {
            userManager = usrMgr;
            roleManager = roleMgr;
            //passwordHasher = passwordHash;
        }



        #region Miscellaneous Admin Work

    
        public IActionResult AdminHome()
        {
            return View();
        }



        #endregion



        #region User Management

        [AllowAnonymous]
        public IActionResult CreateUser()
        {

            CreateUserViewModel model = new CreateUserViewModel();
            model.YesNoList = PopulateYesNo();

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel appUser)
        {

            if (!string.IsNullOrEmpty(appUser.Id))
            {

                //if (ModelState.IsValid)
                //{
                //    AppUser user = await userManager.FindByIdAsync(appUser.Id);
                //    if (user != null)
                //    {

                //        if (!string.IsNullOrEmpty(appUser.FirstName))
                //            user.FirstName = appUser.FirstName;

                //        if (!string.IsNullOrEmpty(appUser.LastName))
                //            user.LastName = appUser.LastName;

                //        if (!string.IsNullOrEmpty(appUser.Email))
                //            user.Email = appUser.Email;
                //        //else
                //        //    ModelState.AddModelError("", "Enter correct email address!");

                //        if (!string.IsNullOrEmpty(appUser.Password))
                //            user.PasswordHash = passwordHasher.HashPassword(user, appUser.Password);
                //        //else
                //        //    ModelState.AddModelError("", "Password cannot be empty!");

                //        if (!string.IsNullOrEmpty(appUser.UserName) && !string.IsNullOrEmpty(appUser.Email) && !string.IsNullOrEmpty(appUser.Password))
                //        {
                //            IdentityResult result = await userManager.UpdateAsync(user);
                //            if (result.Succeeded)
                //                return RedirectToAction("Index");
                //            else
                //                Errors(result);
                //        }
                //    }
                //    else
                //        ModelState.AddModelError("", "User Not Found!");
                //}

                return View(appUser);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    AppUser newAppUser = new AppUser
                    {
                        FirstName = appUser.FirstName,
                        LastName = appUser.LastName,
                        UserName = appUser.UserName,
                        Email = appUser.Email,
                        PhoneNumber = appUser.PhoneNumber

                    };

                    if (appUser.YesNoId == 1)
                        newAppUser.IsActive = true;
                    else
                        newAppUser.IsActive = false;


                    IdentityResult result = await userManager.CreateAsync(newAppUser, appUser.Password);

                    if (result.Succeeded)
                    {
                        await userManager.AddToRoleAsync(newAppUser, "Customer");
                        return RedirectToAction("Index", "Home", new { area = "" });
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
                }
                }
                return View("CreateUser", appUser);

            }



        }

        public async Task<IActionResult> ManageProfile()
        {

            AppUser user = await userManager.GetUserAsync(User);

            if (user != null)
            {
                UserProfileViewModel userProfileViewModel = new UserProfileViewModel
                {

                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    PhoneNumber = user.PhoneNumber,
                    Email = user.Email,
                    ProfilePicture = user.ProfilePicture
                };

                return View(userProfileViewModel);
            }
            else
                return RedirectToAction("Index", "Home", new { area = "" });


        }

        [HttpPost]
        public async Task<IActionResult> SaveProfile(UserProfileViewModel model)
        {

            if (ModelState.IsValid)
            {
                AppUser user = await userManager.GetUserAsync(User);

                if (user != null)
                {

                    if (!string.IsNullOrEmpty(model.UserName) && !string.IsNullOrEmpty(model.FirstName) && !string.IsNullOrEmpty(model.LastName) && !string.IsNullOrEmpty(model.PhoneNumber))
                    {
                        user.UserName = model.UserName;
                        user.FirstName = model.FirstName;
                        user.LastName = model.LastName;
                        user.PhoneNumber = model.PhoneNumber;
                        user.Email = model.Email;


                        if (Request.Form.Files.Count > 0)
                        {
                            IFormFile file = Request.Form.Files.FirstOrDefault();
                            using (var dataStream = new MemoryStream())
                            {
                                await file.CopyToAsync(dataStream);
                                user.ProfilePicture = dataStream.ToArray();
                            }
                            //await userManager.UpdateAsync(user);
                        }

                        IdentityResult result = await userManager.UpdateAsync(user);
                        if (result.Succeeded)
                            return RedirectToAction("ManageProfile");
                        else
                            Errors(result);
                    }
                }
                else
                    ModelState.AddModelError("", "User Not Found!");

            }

            return View("ManageProfile", model);

        }

        public IActionResult ManageAddress()
        {
            return View();
        }

        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePassword(ChangePasswordViewModel model)
        {

            if (ModelState.IsValid)
            {
                AppUser user = await userManager.GetUserAsync(User);

                if (user != null)
                {

                    IdentityResult result = await userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("ChangePassword");

                    }
                    else
                        Errors(result);
                }
                else
                    ModelState.AddModelError("", "User Not Found!");

            }

            return View("ManageProfile", model);


        }

        [HttpPost]
        public async Task<IActionResult> UpdatePassword2(ChangePasswordViewModel model)
        {

            if (ModelState.IsValid)
            {
                AppUser user = await userManager.GetUserAsync(User);

                if (user != null)
                {
                    IdentityResult result = await userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);

                    if (result.Succeeded)
                    {
                        return Json(new { success = true, Data = "Password was changed successfully." });
                  
                        //Result callResult = new Result();
                        //callResult.Success = true;
                        //callResult.Data = "Password was changed successfully.";

                        //return Json(callResult);

                    }
                    else
                        return Json(new { success = false, Data = result.Errors.ToList().FirstOrDefault() });
                }
                else
                    return Json(new { success = false, Data = "User does not exist." });
            }

            return Json(new { success = false, Data = "Model not valid." });

        }


        public async Task<IActionResult> ViewUsers()
        {
            var users = await userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (AppUser user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;

CakesByRAndRCore/Views/AdminAndSetup/AddRole.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Role Manager";

}
<div class="row">

    <br />
    <div class="content-form-title"> <h2 id="title" style="font-size:20px;">Create Role:</h2></div>
    <br />

    <div class="col-md-4">
        <form method="post" asp-action="AddRole" asp-controller="AdminAndSetup">
@*            <div class="input-group">
                <input name="roleName" class="form-control" autocomplete="rolename" aria-required="true" />
                <span class="input-group-btn">
                    <button class="btn btn-info">Add New Role</button>
                </span>
            </div>*@

            <div class="form-group">
                <label>Enter Role Name:</label>
                <input name="roleName" class="form-control" autocomplete="rolename" aria-required="true" />
            </div>
            <br />
            <button type="submit" id="btnSave" class="btn btn-primary">Save</button>
        </form>
    </div>
    <div class="col-md-8">

        <h4>Available Roles:</h4>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Role Id</th>
                    <th>Role Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var role in Model)
                {
                    <tr>
                        <td>@role.Id</td>
                        <td>@role.Name</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

CakesByRAndRCore/Views/AdminAndSetup/AdminHome.cshtml
@{

    Layout = "~/Views/Shared/_PrivateLayout.cshtml";
}


<div class="container">

    <div class="row offset-md-3" style="text-align:center;vertical-align:top;">
        <img id="homeImg" src="~/images/RAndRLogo.jpg" style="padding-top:5%; max-width:70%; height:auto; padding-bottom:30%; " />
    </div>

</div>

CakesByRAndRCore/Views/AdminAndSetup/ChangePassword.cshtml
@model ChangePasswordViewModel

@{
    ViewData["Title"] = "Change password";
    Layout = "_ManageProfileLayout";
}


@*<h3>@ViewData["Title"]</h3>*@

<br />
<div class="content-form-title"> <h2 id="title" style="font-size:20px;">Change Password:</h2></div>
<br />

<div class="row">
    <div class="col-md-6">
        <form id="change-password-form" method="post" asp-action="UpdatePassword2">
       @* <form id="change-password-form" method="post" asp-action="UpdatePassword2">*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating">
                <input asp-for="OldPassword" class="form-control" autocomplete="current-password" aria-required="true" />
                <label asp-for="OldPassword" class="form-label"></label>
                <span asp-validation-for="OldPassword" class="text-danger"></span>
            </div>

            <div class="form-floating">
                <input asp-for="NewPassword" class="form-control" autocomplete="new-password" aria-required="true" />
                <label asp-for="NewPassword" class="form-label"></label>
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>

            <div class="form-floating">
                <input asp-for="ConfirmNewPassword" class="form-control" autocomplete="new-password" aria-required="true" />
                <label asp-for="ConfirmNewPassword" class="form-label"></label>
                <span asp-validation-for="ConfirmNewPassword" class="text-danger"></span>
            </div>


            <br />
            <button type="submit" id="submit-btn" class="w-25 btn btn-lg btn-primary" onclick="fnSaveData()">Update</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

    <script type="text/javascript">


        $(document).ready(function () {
            $('input').on('keydown', function (e) {
                if (e.key == 'Enter') {
                    e.preventDefault();
                    $("#submit-btn").trigger("click");
                }
            });
            //new CircleType(document.getElementById('txtFull'));
        });


        function AjaxFormSubmit() {

            var url = $("#change-password-form").attr("action");
            var formData = $("#change-password-form").serialize();

            alert("Url: " + url);
            alert(formData);

            $('#change-password-form').on("submit", function (event) {
                event.preventDefault();
                alert("prevented...");
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: formData,
                    processData: false,
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    success: function (response) {
                        if (response.Status) {
                            alert(response.Data);
                        }
                    },
                    error: function () {
                        alert('Failed to update password!');
                    }
                });

            });
        }


        function fnSaveData() {


            //var urlpath = $("#change-password-form").attr("action");
            //var formData = $("#change-password-form").serialize();

            var formData = RAndRJavaScripts.div.getJsonObjectFromDiv('change-password-form', '0');

            //alert("Url: " + urlpath);
            alert("form data: " + formData);

            $('#change-password-form').on("submit", function (event) {
                event.preventDefault();
                alert("prevented...");

            //alert("Not prevented...");

                //RAndRJavaScripts.ajaxLoder.showPleaseWait();

                //RAndRJavaScripts.actionCall(urlpath, { model: formData }, "POST", function (data, result) {
                    
                //    alert("Result: " + result.Data);
                    
                //    if (result) {
                //        RAndRJavaScripts.ajaxLoder.hidePleaseWait();
                //        RAndRJavaScripts.message.showInfo('#showMsg', data.Data, 4000);
                //        fnResetData();
                //        $('html, body').animate({ scrollTop: 0 }, 'slide');
                //        if ($updateMode == true) {
                //            setTimeout(function () {
                //                window.location.href = '/AdminAndSetup/ManageProfile';
                //                //history.back();
                //            }, 3000);
                //        }
                //    } else {
                //        RAndRJavaScripts.ajaxLoder.hidePleaseWait();
                //        RAndRJavaScripts.message.showError('#showErrorMsg', data.Data, 10000);
                //    }
                //});
                $.ajax({
                    type: "POST",
                    url: '/AdminAndSetup/UpdatePassword2',
                    data: formData,
                    dataType: 'json',
                    success: function (response, status, jqXHR) {
                   
                        //if (callbackFn != null || callbackFn != undefined) {
                        //    if (response != null && response.success) callbackFn(response, true);
                        //    else callbackFn(response, false);
                        //}
              
                        //RAndRJavaScripts.ajaxLoder.hidePleaseWait();
                        //RAndRJavaScripts.message.showInfo('#showMsg', response.Data, 4000);

                    //alert('Successfully received Data ');
                    alert("Success: " + response.Data);
                    RAndRJavaScripts.tools.resetPage('change-password-form', null, null, null, null, null, 'FullName');
                   
                    },
                    error: function (jqXHR, status, error) {
                        
                        //RAndRJavaScripts.ajaxLoder.hidePleaseWait();
                        //RAndRJavaScripts.message.showError('#showErrorMsg', data.Data, 10000);

                        alert("Error: " + response.Data);

                        //if (callbackFn != null || callbackFn != undefined) {
                        //    var err = jqXHR.responseText;
                        //    // err = err.substring(err.indexOf("<title>"), err.indexOf("<meta")).replace('<title>', '').replace('<meta', '');
                        //    callbackFn(err, false);
                        //}
                    }
                });

            });

        }

        //function fnResetData() {
        //    RAndRJavaScripts.tools.resetPage('formDiv', null, null, null, null, null, 'FullName');
        //}


    </script>

CakesByRAndRCore/Views/AdminAndSetup/CreateUser.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


@model CreateUserViewModel
@{
    ViewData["Title"] = "Create User";
}


@*<a asp-action="Home/Index" class="btn btn-secondary">Back</a>*@
<div asp-validation-summary="All" class="text-danger"></div>

<div class="col-md-8 offset-md-1" style="padding-top:50px">


    <form method="post" asp-action="Create">

@*        <br />
        <br />
        <br />*@
        <div class="content-form-title" > <h2 id="title" style="font-size:20px;">Create User:</h2></div>

        <div class="form-group">
            <div class="col-md-2">
                <input asp-for="Id" class="form-control" hidden />
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">

                <div class="form-group">
                    <label asp-for="FirstName"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" style="color: red;"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" style="color: red;"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserName"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" style="color: red;"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" style="color: red;"></span>
                </div>


                <div class="form-group">
                    <br />
                </div>

                @* <button type="submit" id="btnSave" class="btn btn-primary" onclick="ShowAlert()">Create</button>*@

                <button type="submit" id="btnSave" class="btn btn-primary">Save</button>

            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" style="color: red;"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" style="color: red;"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" style="color: red;"></span>
                </div>



                <div class="form-group">
                    <label asp-for="YesNoList"></label>
                    @Html.DropDownListFor(m => m.YesNoId, Model.YesNoList, new { @class = "form-control" })
                </div>





            </div>
        </div>
    </form>

</div>


@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @*    <partial name="_ValidationScriptsPartial" />*@

}

CakesByRAndRCore/Views/AdminAndSetup/ManageAddress.cshtml
@{

    Layout = "_ManageProfileLayout";
}



<h4>You are in Manage Address page!</h4>

CakesByRAndRCore/Views/AdminAndSetup/ManageProfile.cshtml
@model UserProfileViewModel

@{
    ViewData["Title"] = "Profile";
    Layout = "_ManageProfileLayout";
}

<br />
<div class="content-form-title"> <h2 id="title" style="font-size:20px;">Profile:</h2></div>
<br />

<form id="profile-form" method="post" asp-action="SaveProfile" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <br />
            <button id="update-profile-button" type="submit" class="btn btn-primary">Save</button>
        </div>
        <div class="col-md-8">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProfilePicture" style="width: 100%;"></label>
                @if (Model.ProfilePicture != null)
                {
                    <img id="profilePicture" style="width:350px;height:350px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(Model.ProfilePicture))">
                }
                else
                {
                    <img id="profilePicture" style="width:350px;height:350px; object-fit:cover" src="">
                }
                <input type="file"
                       accept=".png,.jpg,.jpeg,.gif,.tif"
                       asp-for="ProfilePicture"
                       class="form-control"
                       style="border:0px!important;padding: 0px;padding-top: 10px;padding-bottom: 30px;"
                       onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
        </div>

    </div>
</form>


@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @*    <partial name="_ValidationScriptsPartial" />*@

}

CakesByRAndRCore/Views/AdminAndSetup/ManageUserRoles.cshtml
@model List<ManageUserRolesViewModel>
@{
    ViewData["Title"] = "Manage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post">
    <div class="card">
        <div class="card-header">
            <br />
            <div class="content-form-title"> <h2 id="title" style="font-size:20px;">Roles for user: @ViewBag.UserName</h2></div>
            <br />
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId" />
                    <input type="hidden" asp-for="@Model[i].RoleName" />
                    <input asp-for="@Model[i].Selected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].Selected">
                        @Model[i].RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary"
                   style="width:auto" asp-controller="AdminAndSetup" asp-action="SaveUserRoles" asp-route-userId="@ViewBag.userId" />

            <input type="submit" class="btn btn-primary" value="Cancel" asp-controller="AdminAndSetup" asp-action="ViewUsers" />
        </div>
    </div>
</form>

CakesByRAndRCore/Views/AdminAndSetup/ViewUsers.cshtml
@model List<CakesByRAndRCore.Models.UserRolesViewModel>
@{
    ViewData["Title"] = "Index";

}


<div class="col-md-8 offset-md-2">
    <br />
    <div class="content-form-title"> <h2 id="title" style="font-size:20px;">Users:</h2></div>
    <br />
<table class="table ">
    <thead>
        <tr>
            <th>User Name</th>
@*            <th>Last Name</th>*@
            <th>Email</th>
            <th>Roles</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                    <td>@user.FirstName  @user.LastName</td>
@*                <td>@user.LastName</td>*@
                <td>@user.Email</td>
                <td>@string.Join(" , ", user.Roles.ToList())</td>
                <td>
                        <a class="btn btn-primary" asp-controller="AdminAndSetup" asp-action="ManageUserRoles" asp-route-userId="@user.UserId">Manage Roles</a>
                </td>
            </tr>
        }
    </tbody>
</table>

</div>